### ISSUE TITLE
Redux Integration

### ISSUE THREAD

**Issue by HZSamir** [kyaroru/ReactNavDrawer#4]
Hello,
first of all thank you for this example
I am having trouble hooking up the nav reducer to my redux store. The state is there, but no action is fired on navigating.

How would you do it?
Thank you.

**Comment by kyaroru** [comment]
hi, this example is without redux. to view example with redux: https://github.com/kyaroru/ReactNavDrawerRedux

however, if issue like this happen i would first check my root reducer - check the existence of nav reducer. 

then, i will check my component <AppNavigator> to see whether it has addNavigationHelper() method :p 

example of code: 
`
      <AppNavigator
        navigation={addNavigationHelpers({
          dispatch,
          state: nav,
        })}
      />
`

**Comment by HZSamir** [comment]
Thank you so much for taking the time
I'll get to it now
Good day to you :)
