### ISSUE TITLE
Bring nested navigator to top

### ISSUE THREAD

**Issue by HZSamir** [kyaroru/ReactNavDrawer#5]
Hello again,
I have a nested `StackNavigator` inside my `DrawerNavigator` like so:

```javascript
const SomeStack = StackNavigator({
  Counter: {screen: CounterScreen},
  Color: {screen: ColorScreen}
});

const Drawer = DrawerNavigator({
  HomeScreen: { screen: HomeScreen, navigationOptions: homeNavOptions },
  UserScreen: { screen: CounterScreen, navigationOptions: userNavOptions },
  CounterScreen: { screen: SomeStack, navigationOptions: counterNavOptions },
}, {...getDrawerConfig(300, 'left', 'HomeScreen'), contentComponent: CustomDrawerContentComponent});
```

However, as you can see in the following screenshot, the nested header appears below the Drawer's header, even when I navigate inside it

![screen](https://user-images.githubusercontent.com/4499783/33541687-4d089d98-d8d0-11e7-9946-7c56bd3063bc.png)
![screen2](https://user-images.githubusercontent.com/4499783/33541708-5b9bda78-d8d0-11e7-8aff-196fbac03773.png)

Forcing me to later hide it, making using the back button to navigate back impossible.
Is there some way to have the nested navigator come up, on top the drawernavigator; even though I could still swipe to display it?
This seems to be the default behaviour according to [this
](https://reactnavigation.org/docs/intro/nesting)
I have scoured the docs and SO questions to no avail, and so now I turn to you.

Thank you very much in advance

**Comment by kyaroru** [comment]
Hi,

Usually in this case I will just set headerMode: ‘none’ to the child StackNavigator & DrawerNavigator and implement my custom NavBar to handle the back behavior :p

Regards,
Carol

On 4 Dec 2017, 15:53 +0800, Unforgiven-wanda <notifications@github.com>, wrote:

Hello again,
I have a nested StackNavigator inside my DrawerNavigator like so:

const SomeStack = StackNavigator({
  Counter: {screen: CounterScreen},
  Color: {screen: ColorScreen}
});

const Drawer = DrawerNavigator({
  HomeScreen: { screen: HomeScreen, navigationOptions: homeNavOptions },
  UserScreen: { screen: CounterScreen, navigationOptions: userNavOptions },
  CounterScreen: { screen: SomeStack, navigationOptions: counterNavOptions },
}, {...getDrawerConfig(300, 'left', 'HomeScreen'), contentComponent: CustomDrawerContentComponent});

However, as you can see in the following screenshot, the nested header appears below the Drawer's header, even when I navigate inside it

[screen]<https://user-images.githubusercontent.com/4499783/33541687-4d089d98-d8d0-11e7-9946-7c56bd3063bc.png>
[screen2]<https://user-images.githubusercontent.com/4499783/33541708-5b9bda78-d8d0-11e7-8aff-196fbac03773.png>

Forcing me to later hide it, making using the back button to navigate back impossible.
Is there some way to have the nested navigator come up, on top the drawernavigator; even though I could still swipe to display it?
This seems to be the default behaviour according to this
<https://reactnavigation.org/docs/intro/nesting>
I have scoured the docs and SO questions to no avail, and so now I turn to you.

Thank you very much in advance
