### ISSUE TITLE
undefined is not an object 

### ISSUE THREAD

**Issue by DalalAbadi** [kyaroru/ReactNavDrawer#6]
I just did npm install and run 

undefined is not an object  (evaluating 'route.routeName')

**Comment by sabiya115** [comment]
same here, please do reply

**Comment by kyaroru** [comment]
Hi, I have fixed the bug (in latest commit). It is due to a breaking changes in react navigation v1.0.0-beta.22 as stated  [in this thread](https://github.com/react-community/react-navigation/issues/3149#issuecomment-352862563)
